version: '3'

services:  
  database:
    build: ./database
#    image: mariadb:10.3
    volumes:
      - /home/lcd/Desktop/macrotis:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    container_name: macrotis-database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=master
      - MYSQL_USER=thor
      - MYSQL_PASSWORD=the_mighty
  macrotis-app:
    build: ./server
    ports:
     - 30000:30000
    depends_on:
      - database
